### ISSUE TITLE
Getting empty array of items when updating a task with feature collection of relations

### ISSUE THREAD

**Issue by amishas157** [osmlab/to-fix-backend#77]
[Here](https://gist.github.com/amishas157/aaa0715da5d0a74117da676f8aaf0e67) is the geojson, which I am trying to update the task with. 
Task id : `miscellaneousbrokenrelationcenmq`

When we try to access the task items, it shows empty array. One another issue is it shows the number of items as 3. 
 
[Link](https://build-to-fix-production.mapbox.com/tasks/miscellaneousbrokenrelationcenmq) to access the task.
[Link](https://build-to-fix-production.mapbox.com/tasks/miscellaneousbrokenrelationcenmq/ibrigtqfvedizc/items) to access all items of task which gives empty array.

cc @geohacker  @ajithranka  @Rub21

**Comment by ajithranka** [comment]
On the backend, i think the `relations` property is also getting nulled before uploading to elastic search. @Rub21 can you confirm?

**Comment by geohacker** [comment]
Still debugging, but I think it's getting dropped here https://github.com/osmlab/to-fix-backend/blob/master/src/utils/formatGeojson.js `formatFeature`

**Comment by batpad** [comment]
My hunch is that the problem is with this `replaceSC` function: https://github.com/osmlab/to-fix-backend/blob/master/src/utils/formatGeojson.js#L89 . I see this function replaces spaces with `_` in  any object keys.

@Rub21 ^ can you clarify? Also, why do we need this? Do we have tasks that send spaces in the keys? I would be fine to just raise an error if there is a space in a property name.

To be more specific, in this case, why it fails is:
  It calls itself recursively here in the case of nested objects (which `relations` is): https://github.com/osmlab/to-fix-backend/blob/master/src/utils/formatGeojson.js#L99

 And most likely fails when it encounters the `geometry` property inside the relation, on this line: https://github.com/osmlab/to-fix-backend/blob/master/src/utils/formatGeojson.js#L98

@Rub21 - do we need to try and do this at all?

@ajithranka - can you think of a more straightforward way to walk down a nested object and replace all spaces in property names with underscores?

**Comment by ajithranka** [comment]
Do we need to replace property names for the entire object?
Would it be enough to do that for just the top-level?

**Comment by geohacker** [comment]
This line https://github.com/osmlab/to-fix-backend/blob/master/src/utils/formatGeojson.js#L90 - gets the relations `Array` on recursion, but then keys will be `[]`.

I'll wait for @Rub21 for context, before fixing this.

**Comment by Rub21** [comment]
The function is replacing strange characters, basically, there is an error in Elastic search when saving certain characters example:Single quotation mark or double quotation mark, also in some keys which beginning with `@` That's why it's dropping .

> can you clarify? Also, why do we need this? Do we have tasks that send spaces in the keys? I would be fine to just raise an error if there is a space in a property name.
There are many 

There are many cases that comes from the data, and one of them is what you mention

I think at this error could be fixed easily, i will try to fix it

**Comment by Rub21** [comment]
@geohacker @batpad @amishas157 @ajithranka  I've fixed the error, I just uploaded your geojson  in staging, https://build-to-fix-staging.tilestream.net/tasks/testhi/zoxyvdawlkscl/items.  I was doing the same thing in production , but got some error, I think it comes from ES. i will check it on Monday.

**Comment by geohacker** [comment]
@Rub21  - thank you for fixing parsing relations!

> The function is replacing strange characters, basically, there is an error in Elastic search when saving certain characters example:Single quotation mark or double quotation mark, also in some keys which beginning with @ That's why it's dropping

Umm this is strange. Can you post the error message here? 

The problem with the above regular expression you have is that it replaces space as well. When I post a JSON with keys from the client-side, I'd expect the server to retain the keys as is - if we ever wanted to parse the JSON on the client with the same keys.

**Comment by Rub21** [comment]
@amishas157 @ajithranka ,  could you try to  create  the task? i already fixed the issues.

**Comment by amishas157** [comment]
Thanks @Rub21 , looks fine on production now. Going to deploy.
